openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
paths:
  /:
    get:
      tags:
        - v1
        - list
      operationId: list_Versions_v2
      summary: List API versions
      responses:
        '200':
          description: |-
            200 response
  /v2:
    get:
      operationId: GetVersionDetailsv2
      summary: Show API version details
    put:
      operationId: saveVersionDetailsv2
      summary: Show API version details
